# jupyter-langs:python

# https://hub.docker.com/_/node
ARG node_version=17.6.0
FROM node:${node_version}-bullseye-slim as nodejs 

# https://hub.docker.com/r/continuumio/miniconda3
# https://github.com/ContinuumIO/docker-images/blob/master/miniconda3/debian/Dockerfile
FROM continuumio/miniconda3:4.10.3

LABEL maintainer="HeRoMo"
LABEL Description="Jupyter lab for Python3 and Javascript"
LABEL Version="5.14.0"

ENV HOME=/root
ENV NOTEBOOK_DIR=/jupyter/notebooks
ENV JUPYTER_DIR=/opt/jupyter
ENV MATPLOTLIBRC=/opt/jupyter

WORKDIR /jupyter

# Install required packages
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
            build-essential \
            cmake \
            gnupg \
            locales \
            fonts-noto-cjk \
            # for ZeroMQ
            libtool \
            libffi-dev \
            libzmq3-dev \
            libczmq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set Locale
ENV LANG=ja_JP.UTF-8
ENV LC_ALL=ja_JP.UTF-8
RUN echo "LC_ALL=ja_JP.UTF-8" >> /etc/environment \
    && echo "ja_JP.UTF-8 UTF-8" >> /etc/locale.gen \
    && echo "LANG=ja_JP.UTF-8" > /etc/locale.conf \
    && locale-gen ja_JP.UTF-8

# Upgrade conda
RUN conda update -n base -c defaults conda
RUN conda install -c conda-forge mamba -y 

# Install Jupyter
RUN mamba update -c conda-forge --all
RUN mamba install -y -c conda-forge  \
                python=3.10.0 \
                pandas \
                scipy \
                bokeh \
                matplotlib \
                # tensorflow \
                keras \
                jupyterlab>=3.2 \
                libiconv \
                ipywidgets>=7.6 \
                ipyleaflet \
                # for dash
                plotly \
                dash \
                lxml \
                xlrd \
                xlwt \
    && conda clean -y --all
# RUN jupyter contrib nbextension install --user
RUN pip install tflearn jupyter_dash

RUN mkdir -p $NOTEBOOK_DIR \
    && mkdir -p $JUPYTER_DIR \
    && mkdir -p $MATPLOTLIBRC
COPY conf/matplotlibrc $MATPLOTLIBRC/matplotlibrc
COPY conf/jupyter_notebook_config.py $JUPYTER_DIR/jupyter_notebook_config.py

# Install Javascript
ENV NODE_VERSION ${node_version}
ENV YARN_VERSION 1.22.17
RUN mkdir -p /opt
COPY --from=nodejs /opt/yarn-v${YARN_VERSION} /opt/yarn
COPY --from=nodejs /usr/local/bin/node /usr/local/bin/
COPY --from=nodejs /usr/local/lib/node_modules/ /usr/local/lib/node_modules/
RUN ln -s /opt/yarn/bin/yarn /usr/local/bin/yarn \
    && ln -s /opt/yarn/bin/yarn /usr/local/bin/yarnpkg \
    && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
    && ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm \
    && ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npx
RUN yarn global add typescript tslab \
    && tslab install \
    && yarn add @types/node

# Install jupyter labextensions
RUN jupyter labextension install \
            @jupyter-widgets/jupyterlab-manager \
            jupyterlab-plotly \
            plotlywidget \
            jupyter-leaflet

# for JupyterLab
EXPOSE 8888
# for Dash
EXPOSE 8050

CMD ["jupyter", "lab", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--notebook-dir=/jupyter/notebooks", "--config=$JUPYTER_DIR/jupyter_notebook_config.py"]
