# jupyter-langs:python
FROM buildpack-deps:buster

LABEL   Maintainer="HeRoMo" \
        Description="Jupyter lab for Python3" \
        Version="3.0.0"

ENV HOME=/root \
    NOTEBOOK_DIR=/notebooks \
    JUPYTER_DIR=/opt/jupyter \
    MATPLOTLIBRC=/opt/jupyter

# Install required packages
RUN echo "deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_10/ ./" >> /etc/apt/sources.list && \
    wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_10/Release.key -O- | apt-key add
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
                    apt-utils \
                    cmake \
                    locales \
                    fonts-noto-cjk \
                    # for ZeroMQ
                    libtool \
                    libffi-dev \
                    libzmq3-dev \
                    libczmq-dev \
    && rm -rf /var/lib/apt/lists/*

# Set Locale
ENV LANG=ja_JP.UTF-8 \
    LC_ALL=ja_JP.UTF-8
RUN echo "LC_ALL=ja_JP.UTF-8" >> /etc/environment \
    && echo "ja_JP.UTF-8 UTF-8" >> /etc/locale.gen \
    && echo "LANG=ja_JP.UTF-8" > /etc/locale.conf \
    && locale-gen ja_JP.UTF-8

# Install Anaconda and Jupyter
ENV CONDA_VERSION=2020.02
RUN wget https://repo.continuum.io/archive/Anaconda3-${CONDA_VERSION}-Linux-x86_64.sh && \
    chmod 755 ./Anaconda3-${CONDA_VERSION}-Linux-x86_64.sh && \
    ./Anaconda3-${CONDA_VERSION}-Linux-x86_64.sh -b
ENV PATH=$HOME/anaconda3/bin:$PATH
RUN conda install python=3.7
RUN conda install -y -c conda-forge  \
                pandas \
                scipy \
                bokeh \
                matplotlib \
                tensorflow \
                keras \
                jupyter \
                jupyterlab \
                libiconv \
                jupyter_contrib_nbextensions \
    && conda build purge-all
RUN jupyter contrib nbextension install --user
RUN pip install tflearn

RUN mkdir -p $NOTEBOOK_DIR && \
    mkdir -p $JUPYTER_DIR && \
    mkdir -p $MATPLOTLIBRC
COPY conf/matplotlibrc $MATPLOTLIBRC/matplotlibrc
COPY conf/jupyter_notebook_config.py $JUPYTER_DIR/jupyter_notebook_config.py

EXPOSE 8888
#CMD ["jupyter", "notebook", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--notebook-dir=/mnt/notebooks"]
CMD ["jupyter", "lab", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--notebook-dir=/notebooks", "--config=$JUPYTER_DIR/jupyter_notebook_config.py"]
