# jupyter-langs:ruby
# VERSION 0.9.2
FROM hero/jupyter-langs:zeromq

MAINTAINER HeRoMo

ENV HOME=/root RUBY_VERSION=2.4.2
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
                    gsl-bin \
                    libgsl0-dev

RUN git clone https://github.com/rbenv/rbenv.git $HOME/.rbenv && \
    mkdir -p $HOME/.rbenv/plugins && \
    git clone https://github.com/rbenv/ruby-build.git $HOME/.rbenv/plugins/ruby-build && \
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> $HOME/.bashrc && \
    echo 'eval "$(rbenv init -)"' >> $HOME/.bashrc
ENV PATH=$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH
RUN rbenv install $RUBY_VERSION && \
    rbenv global $RUBY_VERSION
RUN eval "$(rbenv init -)"
RUN LD_LIBRARY_PATH=/usr/local/lib \
    gem install --no-ri --no-rdoc \
                cztop \
                sciruby \
                daru \
                nyaplot \
                #sciruby-full \
                bundler \
                iruby
RUN iruby register --force

CMD ["jupyter", "lab", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--notebook-dir=/notebooks"]
