# jupyter-langs:all
# VERSION 1.4.0
FROM hero/jupyter-langs:zeromq

# Install SPARQL
RUN pip install sparqlkernel && \
    jupyter sparqlkernel install

# Install R
RUN conda install --quiet --yes \
            'r-base' \
            'r-irkernel' \
            'r-plyr' \
            'r-devtools' \
            'r-tidyverse' \
            'r-shiny' \
            'r-rmarkdown' \
            'r-forecast' \
            'r-rsqlite' \
            'r-reshape2' \
            'r-nycflights13' \
            'r-caret' \
            'r-rcurl' \
            'r-crayon' \
            'r-randomforest' \
            'r-tensorflow' \
    && conda build purge-all

# Install Javascript
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash - && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
        yarn \
        nodejs \
    && rm -rf /var/lib/apt/lists/*
RUN yarn global add ijavascript && \
    ijsinstall

# Install anyenv
ENV SHELL=/bin/bash
RUN git clone https://github.com/anyenv/anyenv $HOME/.anyenv && \
    echo 'export PATH="$HOME/.anyenv/bin:$PATH"' >> ~/.bashrc && \
    echo 'eval "$(anyenv init -)"' >> $HOME/.bashrc && \
    exec $SHELL -l
ENV PATH="$HOME/.anyenv/bin:$PATH"
RUN anyenv install --force-init

# Install Ruby
ENV RUBY_VERSION=2.6.1
RUN anyenv install rbenv && \
    eval "$(anyenv init -)" && \
    rbenv install ${RUBY_VERSION} && \
    rbenv global $RUBY_VERSION
RUN eval "$(anyenv init -)" && \
    gem install --no-document \
                cztop \
                sciruby \
                daru \
                nyaplot \
                iruby \
    && iruby register --force

# golang Install
ENV GO_VERSION=1.11.5 \
    GOPATH=/go
ENV PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
RUN wget -O go.tgz https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go.tgz && \
    rm go.tgz
RUN go get -u github.com/gopherdata/gophernotes && \
    mkdir -p $HOME/.local/share/jupyter/kernels/gophernotes && \
    cp -r /go/src/github.com/gopherdata/gophernotes/kernel/* $HOME/.local/share/jupyter/kernels/gophernotes

