# jupyter-langs:r
# VERSION 1.2.0
FROM hero/jupyter-langs:python

MAINTAINER HeRoMo

# Install R
RUN conda install --quiet --yes \
          'r-base' \
          'r-irkernel' \
          'r-plyr' \
          'r-devtools' \
          'r-tidyverse' \
          'r-shiny' \
          'r-rmarkdown' \
          'r-forecast' \
          'r-rsqlite' \
          'r-reshape2' \
          'r-nycflights13' \
          'r-caret' \
          'r-rcurl' \
          'r-crayon' \
          'r-randomforest' \
          'r-tensorflow' \
    && conda clean -tipsy
