# jupyter-langs:ruby
# VERSION 1.2.0
FROM hero/jupyter-langs:zeromq

MAINTAINER HeRoMo

ENV HOME=/root \
    NODE_VERSION=8.9.0

RUN git clone https://github.com/riywo/ndenv $HOME/.ndenv && \
    mkdir -p $HOME/.ndenv/plugins && \
    git clone https://github.com/riywo/node-build.git $HOME/.ndenv/plugins/node-build && \
    git clone https://github.com/pine/ndenv-yarn-install.git $HOME/.ndenv/plugins/ndenv-yarn-install && \
    echo 'export PATH="$HOME/.ndenv/bin:$PATH"' >> $HOME/.bashrc && \
    echo 'eval "$(ndenv init -)"' >> $HOME/.bashrc
ENV PATH=$HOME/.ndenv/bin:$HOME/.ndenv/shims:$PATH
RUN ndenv install $NODE_VERSION && \
    ndenv global $NODE_VERSION
RUN eval "$(ndenv init -)" && \
    yarn global add ijavascript jp-babel && \
    ijsinstall && \
    jp-babel-install
