# jupyter-langs:python
# VERSION 1.1.0
FROM buildpack-deps:stretch

MAINTAINER HeRoMo

ENV HOME=/root \
    NOTEBOOK_DIR=/notebooks \
    JUPYTER_DIR=/opt/jupyter \
    MATPLOTLIBRC=/opt/jupyter

# Install required packages
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
                    apt-utils \
                    fonts-noto-cjk \
    && rm -rf /var/lib/apt/lists/*

# Install Anaconda and Jupyter
ENV CONDA_VERSION=5.0.1
RUN wget https://repo.continuum.io/archive/Anaconda3-${CONDA_VERSION}-Linux-x86_64.sh && \
    chmod 755 ./Anaconda3-${CONDA_VERSION}-Linux-x86_64.sh && \
    ./Anaconda3-${CONDA_VERSION}-Linux-x86_64.sh -b
ENV PATH=$HOME/anaconda3/bin:$PATH
RUN conda install -y jupyter notebook pandas bokeh matplotlib && \
    conda install -y -c conda-forge jupyterlab \
                        jupyter_contrib_nbextensions && \
    jupyter contrib nbextension install --user

RUN mkdir -p $NOTEBOOK_DIR && \
    mkdir -p $JUPYTER_DIR && \
    mkdir -p $MATPLOTLIBRC
COPY conf/matplotlibrc $MATPLOTLIBRC/matplotlibrc
COPY conf/jupyter_notebook_config.py $JUPYTER_DIR/jupyter_notebook_config.py

EXPOSE 8888
#CMD ["jupyter", "notebook", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--notebook-dir=/mnt/notebooks"]
CMD ["jupyter", "lab", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--notebook-dir=/notebooks", "--config=$JUPYTER_DIR/jupyter_notebook_config.py"]
