FROM jupyter-langs:latest

MAINTAINER HeRoMo

ENV RUBY_VERSION=2.4.2
RUN echo "deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/ ./" >> /etc/apt/sources.list && \
    wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key -O- | apt-key add
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
                    libtool \
                    libffi-dev \
                    libzmq3-dev \
                    libczmq-dev

RUN git clone https://github.com/rbenv/rbenv.git $HOME/.rbenv && \
    mkdir -p $HOME/.rbenv/plugins && \
    git clone https://github.com/rbenv/ruby-build.git $HOME/.rbenv/plugins/ruby-build && \
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> $HOME/.bashrc && \
    echo 'eval "$(rbenv init -)"' >> $HOME/.bashrc
RUN $HOME/.rbenv/bin/rbenv install $RUBY_VERSION && \
    $HOME/.rbenv/bin/rbenv global $RUBY_VERSION
RUN eval "$($HOME/.rbenv/bin/rbenv init -)"
RUN $HOME/.rbenv/shims/gem install --no-ri --no-rdoc \
                                   cztop \
                                   sciruby \
                                  #  sciruby-full \
                                   iruby
RUN $HOME/.rbenv/shims/iruby register --force

CMD ["jupyter", "lab", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--notebook-dir=/notebooks"]
