# jupyter-langs:zeromq
# VERSION 1.3.1
FROM hero/jupyter-langs:python

MAINTAINER HeRoMo

RUN echo "deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/ ./" >> /etc/apt/sources.list && \
    wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key -O- | apt-key add
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
                    libtool \
                    libffi-dev \
                    libzmq3-dev \
                    libczmq-dev \
    && rm -rf /var/lib/apt/lists/*
