name: Hello World
on:
  push:
    branches:
      - test-workflow
jobs:
  hello-world:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: echo "hello-world"
      - run: uname -a
      - run: lscpu