name: Publish Python Docker image
on:
  push:
    branches:
      - main
      - upgrade-python-and-nodejs
    tags:
      - 'python-[0-9]+.[0-9]+.[0-9]+'
    # paths:
    #   - Dockerfile-python
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-image:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/python
          tags: |
            type=ref,event=branch
            type=match,pattern=python-(.*),group=1
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-python
          platforms: linux/amd64,linux/arm64
          push: true
          # tags: ${{ steps.meta.outputs.tags }}
          tags: test
          labels: ${{ steps.meta.outputs.labels }}
